# Generated by Django 4.2.7 on 2023-11-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_received', models.CharField(max_length=50)),
                ('received_from', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=100)),
                ('document_date', models.CharField(max_length=50)),
                ('particulars', models.TextField()),
                ('copies', models.TextField()),
                ('date_signed_sa', models.CharField(max_length=50)),
                ('transmittal_number', models.CharField(max_length=50)),
                ('date_sent_out', models.CharField(max_length=50)),
                ('date_received_from_region', models.CharField(max_length=50)),
                ('date_received_by_region', models.CharField(max_length=50)),
                ('location_stored', models.TextField()),
                ('date_sent_to_teams', models.CharField(max_length=50)),
                ('received_by_team', models.CharField(max_length=50)),
            ],
        ),
    ]
