# Generated by Django 4.2.7 on 2023-11-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_toregion_date_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_doccument', models.CharField(max_length=100)),
                ('addressee', models.CharField(max_length=200)),
                ('document_date', models.DateField()),
                ('subject', models.TextField()),
                ('details', models.CharField(max_length=200)),
                ('reference_number', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('received_from', models.CharField(max_length=100)),
                ('date_sentout_from_osa', models.DateField()),
                ('team_receiver', models.CharField(max_length=100)),
                ('location_stored', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='toregion',
            name='remarkds',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
