# Generated by Django 4.2.7 on 2023-11-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fromregion_toregion_remarkds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toregion',
            old_name='remarkds',
            new_name='remarks',
        ),
    ]
