# Generated by Django 4.2.7 on 2023-11-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_toregion_copies_alter_toregion_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toregion',
            name='copies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='date_received_by_region',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='date_received_from_region',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='date_sent_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='date_sent_to_teams',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='date_signed_sa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='location_stored',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='particulars',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='received_by_team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='received_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toregion',
            name='transmittal_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
